name: Build on Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: |
        cmake -G "NMake Makefiles" .
        nmake
