name: "pre-release"
on:
  push:
    branches:
      - "main"
jobs:
  pre-release:
    name: "Pre release"
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Prepare environment
      id: prep
      run: |
        Add-Content -Path $env:GITHUB_ENV "WORKSPACE_MSYS2=/$($env:GITHUB_WORKSPACE -replace ':?\\','/')"
        Add-Content -Path $env:GITHUB_ENV "MSYSTEM=MINGW64"
        Add-Content -Path $env:GITHUB_ENV "MSYS2_PATH_TYPE=inherit"
    - name: Install msys2
      run: choco install msys2
    - name: Install tools and libraries
      run: |
        .\scripts\run-sh.ps1 "install-mingw.sh"
    - name: Build
      run: |
        .\scripts\run-sh.ps1 "build.sh"
    - name: Package
      run: |
        .\scripts\run-sh.ps1 "package.sh"
        cd dist
        choco pack
        cd ..
    - name: Prerelease
      run: |
        .\scripts\run-sh.ps1 "prerelease.sh"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
